=== missingfield/PhysicallyBasedForB/PhysicallyBasedB3D/schema/schema-lightsources.json
{
  "$schema": "http://json-schema.org/schema",
  "title": "Light",
  "description": "A light source.",
  "type": "array",
  "items": {
    "additionalProperties": false,
    "properties": {
      "name": {
        "description": "Name of the light source.",
        "type": "string",
        "default": "Name"
      },
      "temperature": {
        "description": "Color temperature in Kelvin.",
        "type": "number",
        "default": 6500
      },
      "temperatureRange": {
        "description": "The typical range of color temperature for this specific light source.",
        "type": "array",
        "items": {
          "type": "number"
        },
        "default": [6500, 7000],
        "minItems": 2,
        "maxItems": 2
      },
      "intensity": {
        "type": "number",
        "default": 0
      },
      "intensityRange": {
        "description": "The typical range of intensity for this specific light source.",
        "type": "array",
        "items": {
          "type": "number"
        },
        "default": [0, 1],
        "minItems": 2,
        "maxItems": 2
      },
      "unit": {
        "type": "array",
        "items": {
          "enum": ["lm", "lx", "cd/m2"]
        },
        "minItems": 1,
        "maxItems": 1
      },
      "type": {
        "description": "The type of light, for DCC applications.",
        "type": "array",
        "items": {
          "enum": [
            "directional",
            "surface",
            "spot",
            "point",
            "cylinder",
            "dome"
          ]
        },
        "minItems": 1,
        "maxItems": 1
      },
      "category": {
        "type": "array",
        "items": {
          "enum": ["Artificial", "Natural"]
        },
        "minItems": 1,
        "maxItems": 1
      },
      "description": {
        "description": "This field should be used for disclaimers and other useful info for CG artists that may affect the way they use the values. It's totally fine to leave this empty.",
        "type": "string",
        "maxLength": 500
      },
      "sources": {
        "description": "Provide at least one source for the values.",
        "type": "array",
        "items": {
          "type": "string",
          "minLength": 1
        },
        "minItems": 1,
        "uniqueItems": true
      },
      "tags": {
        "description": "Tags",
        "type": "array",
        "items": {
          "type": "string"
        },
        "uniqueItems": true
      }
    },
    "required": [
      "name",
      "temperature",
      "intensity",
      "unit",
      "category",
      "description",
      "sources"
    ]
  }
}

=== missingfield/PhysicallyBasedForB/PhysicallyBasedB3D/cached_data/lights.json
[{"name": "Candle Flame", "temperature": 1850, "intensity": 13, "unit": ["lm"], "type": ["point"], "category": ["Natural"], "description": "", "sources": ["https://en.wikipedia.org/wiki/Candle#Characteristics", "https://en.wikipedia.org/wiki/Color_temperature"]}, {"name": "Car Headlight (Halogen)", "temperature": 3500, "intensity": 1500, "intensityRange": [700, 2000], "unit": ["lm"], "type": ["spot"], "category": ["Artificial"], "description": "Tungsten-halogen bulbs, commonly just called halogen, are the most widely used bulbs in car headlights. High beam is approximately double the intensity of a low beam.", "sources": ["https://www.bulbfacts.com/halogen-bulbs/chart/", "https://en.wikipedia.org/wiki/Headlamp#Light_sources"]}, {"name": "Digital Display", "temperature": 6500, "intensity": 200, "intensityRange": [100, 2000], "unit": ["cd/m2"], "type": ["surface"], "category": ["Artificial"], "description": "Displays like computer monitors, TVs, signage, etc. Typically they have a temperature of 6500K but it can vary. The sRGB spec for monitors targets 80 cd/m2. Typically, monitors calibrated for broadcast or studio color grading should have a brightness of 100 cd/m2 in Japan and in the United States, or 120 cd/m2 in the European Union. This is however considered quite dark for normal use, so consumer monitors tend to be brighter.", "sources": ["https://www.digitalview.com/blog/lcd-panels-backlights-brightness/", "https://en.wikipedia.org/wiki/Color_temperature", "https://en.wikipedia.org/wiki/Candela_per_square_metre"], "tags": ["computer", "monitor", "lcd", "oled", "screen"]}, {"name": "Firefly", "temperature": 0, "intensity": 0.0006, "unit": ["lm"], "type": ["point"], "category": ["Natural"], "description": "Fireflies produce a \"cold light\", with no infrared or ultraviolet frequencies. The light may be yellow, green, or pale red, with wavelengths from 510 to 670 nanometers. Some species such as the dimly glowing \"blue ghost\" of the Eastern US may seem to emit blueish-white light from a distance and in low light conditions, but their glow is bright green when observed up close. Their perceived blue tint may be due to the Purkinje effect.", "sources": ["https://what-if.xkcd.com/151/", "https://www.nature.com/articles/s41598-021-91839-3", "https://en.wikipedia.org/wiki/Firefly"], "tags": ["bioluminescence"]}, {"name": "Fluorescent Tube Light", "temperature": 5000, "intensity": 1000, "intensityRange": [500, 5000], "unit": ["lm"], "type": ["cylinder"], "category": ["Artificial"], "description": "", "sources": ["https://en.wikipedia.org/wiki/Fluorescent_lamp", "https://www.homedepot.com/b/Lighting-Light-Bulbs-Tube-Lights-Fluorescent-Tube-Lights/N-5yc1vZ2fkol29"]}, {"name": "Kerosene Lamp", "temperature": 1850, "intensity": 50, "intensityRange": [8, 100], "unit": ["lm"], "type": ["point"], "category": ["Natural"], "description": "", "sources": ["https://en.wikipedia.org/wiki/Kerosene_lamp#Performance", "https://en.wikipedia.org/wiki/Color_temperature"]}, {"name": "Household Light Bulb", "temperature": 2700, "temperatureRange": [2400, 6000], "intensity": 800, "intensityRange": [400, 1000], "unit": ["lm"], "type": ["point"], "category": ["Artificial"], "description": "Today's household lightbulbs has a LED light source whereas older light bulbs were using a glowing tungsten filament. LED:s are much much more energy efficient and makes the use of wattage, as a measure of intensity, not very useful. This is why lumen is preferred.", "sources": ["https://en.wikipedia.org/wiki/Incandescent_light_bulb", "https://en.wikipedia.org/wiki/LED_lamp"], "tags": ["incandescent", "tungsten"]}, {"name": "Moon", "temperature": 4100, "intensity": 0.1, "intensityRange": [0.05, 0.32], "unit": ["lx"], "type": ["directional"], "category": ["Natural"], "description": "Technically not a light source, since the light from the moon is simply reflected sunlight. Moonlight is warmer than sunlight due to the surface material of the moon shifting it towards a redder color. Just as sunlight, moonlight is also subject to atmospheric scattering known as Rayleigh scattering, where it goes more towards red during moonrise and moonset. Moonlight is often mistaken to be bluish due to the Purkinje effect.", "sources": ["https://en.wikipedia.org/wiki/Moonlight", "https://en.wikipedia.org/wiki/Moon", "https://en.wikipedia.org/wiki/Purkinje_effect", "https://chrisbrejon.com/cg-cinematography/chapter-4-light-categories/#moon", "https://iopscience.iop.org/article/10.1088/0031-9120/48/3/360", "https://web.archive.org/web/20151005215129/http://www.cast-lighting.com/search/1/display-document/71"]}, {"name": "Photo Flash", "temperature": 5500, "intensity": 20000, "unit": ["lm"], "type": ["spot"], "category": ["Artificial"], "description": "", "sources": ["https://en.wikipedia.org/wiki/Flash_(photography)"], "tags": ["camera"]}, {"name": "Sky (Clear)", "temperature": 15000, "intensity": 20000, "unit": ["lx"], "type": ["dome"], "category": ["Natural"], "description": "Shade illuminated by entire clear blue sky at midday", "sources": ["https://en.wikipedia.org/wiki/Color_temperature", "https://en.wikipedia.org/wiki/Daylight"]}, {"name": "Sky (Moonless Clear Night)", "temperature": 0, "intensity": 0.002, "unit": ["lx"], "type": ["dome"], "category": ["Natural"], "description": "Even a moonless sky casts some light on earth. A phenomenon called airglow, and also starlight, contributes to this. The color of airglow varies", "sources": ["http://stjarnhimlen.se/comp/radfaq.html#10", "https://en.wikipedia.org/wiki/Airglow", "https://en.wikipedia.org/wiki/Starlight", "https://sciencenotes.org/what-is-airglow/"], "tags": ["airglow"]}, {"name": "Sky (Overcast Day)", "temperature": 6500, "intensity": 2000, "intensityRange": [100, 2000], "unit": ["lx"], "type": ["dome"], "category": ["Natural"], "description": "", "sources": ["https://en.wikipedia.org/wiki/Color_temperature", "https://en.wikipedia.org/wiki/Daylight", "https://en.wikipedia.org/wiki/Lux"]}, {"name": "Street Light", "temperature": 0, "intensity": 60000, "intensityRange": [2000, 140000], "unit": ["lm"], "type": ["spot"], "category": ["Artificial"], "description": "The type of yellow light typically used in street lighting is usually a sodium-vapor light. To simulate a sodium-vapor light faithfully you would need a spectral renderer where you can specify the very narrow wavelength range of 589.0 - 589.6 nm in order to get its bespoke monochromatic look.", "sources": ["https://en.wikipedia.org/wiki/Sodium-vapor_lamp", "https://www.1000bulbs.com/fil/categories/high-pressure-sodium-lamps"], "tags": ["sodium", "vapor"]}, {"name": "Sun", "temperature": 5778, "intensity": 100000, "intensityRange": [400, 100000], "unit": ["lx"], "type": ["directional"], "category": ["Natural"], "description": "The changing color of the Sun over the course of the day is mainly a result of the scattering of sunlight and is not due to changes in black-body radiation. The solar illuminance constant is equal to 128 000 lux, but atmospheric extinction brings the number of lux down to around 100 000 lux.", "sources": ["https://en.wikipedia.org/wiki/Color_temperature#The_Sun", "https://en.wikipedia.org/wiki/Sunlight#Measurement", "https://en.wikipedia.org/wiki/Daylight", "http://stjarnhimlen.se/comp/radfaq.html#10", "https://nssdc.gsfc.nasa.gov/planetary/factsheet/sunfact.html"]}]
